version: "3.8"
services:
  card:
    build:
      context: .
      args:
        - CARD=${CARD}
        - NAME=${NAME}
        - COMPANY=${COMPANY}
        - NUMBER=${NUMBER}
        - EMAIL=${EMAIL}
        - WEB=${WEB}
        - ADDRESS=${ADDRESS}
    ports:
      - 8181:80
    env_file:
      - .env