version: "3.8"
services:
  card:
    build:
      context: .
      args:
        - CARD=${CARD}
        - NAME=${NAME}
    ports:
      - 8181:80
    environment:
      - NAME="Barend Botes"
      - CARD=african